package dotenv

import (
	"fmt"
	"os"\n	"sort"
	"strings"
)

// Writer handles writing key-value secrets to a .env file.
type Writer struct {
	filePath string
}

// NewWriter creates a new Writer targeting the given file path.
func NewWriter(filePath string) *Writer {
	return &Writer{filePath: filePath}
}

// Write serializes the provided secrets map into dotenv format and writes
// it to the configured file, overwriting any existing content.
func (w *Writer) Write(secrets map[string]string) error {
	if len(secrets) == 0 {
		return nil
	}

	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by configvault — do not edit manually\n")
	for _, k := range keys {
		v := secrets[k]
		// Quote values that contain spaces or special characters.
		if strings.ContainsAny(v, " \t\n#") {
			v = fmt.Sprintf("%q", v)
		}
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}

	//nolint:gosec // dotenv files are intentionally world-readable in dev.
	return os.WriteFile(w.filePath, []byte(sb.String()), 0644)
}
